# Generated by Django 5.0.4 on 2024-04-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('altura', models.FloatField()),
                ('edad', models.IntegerField()),
                ('raza', models.TextField()),
            ],
        ),
    ]
