# Generated by Django 5.0.4 on 2024-05-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.TextField()),
                ('cedula', models.TextField()),
                ('telefono', models.TextField()),
                ('correo', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='apellido',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='correo',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='telefono',
        ),
    ]
