# Generated by Django 5.0.3 on 2024-06-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cliente_rename_apellido_servicios_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='valor',
            field=models.IntegerField(),
        ),
    ]
